# Generated by Django 2.0.3 on 2018-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='comp_2d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='comprimento 2D'),
        ),
        migrations.AddField(
            model_name='road',
            name='comp_3d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='comprimento 3D'),
        ),
    ]
