# Generated by Django 2.0.3 on 2018-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180720_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='code',
            field=models.CharField(max_length=50, verbose_name='código'),
        ),
    ]
