# Generated by Django 2.0.3 on 2018-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180720_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='código'),
        ),
    ]
